export const R_LABELS = [
    "RAVE ALERT",
    "RCA [SONY]",
    "RECKLESS",
    "REFUNE",
    "REPOPULATE MARS",
    "REPUBLIC/GOOD MUSIC",
    "REVEALED",
    "REVEALED/WALL",
    "ROC-A-FELLA (ISLAND DEF JAM)"
];