export const KNOWN_PAGE_METADATA = new Set(
    [
        "Add",
        "Add a (live) video from this event for a track not listed here",
        "AH.FM",
        "Aliases",
        "Apple Music",
        "Beatport",
        "Charts",
        "Contact",
        "Duration",
        "Export to Spotify",
        "Facebook",
        "General Information",
        "Genres",
        "Go On Air",
        "Google Search",
        "home icon",
        "Hosted Shows / Podcasts",
        "Hot",
        "IDed",
        "Instagram",
        "Last Tracklists",
        "Last Tracks",
        "Last update",
        "like this tracklist",
        "Likes",
        "Member Of",
        "Mix with DJ.Studio",
        "More",
        "Most Liked Tracklists",
        "Most Viewed Tracklists",
        "Most Watched ID's",
        "Most Watched IDs",
        "on",
        "Posted at",
        "Posted by",
        "Producer Chart Ranks",
        "Related Tracklists",
        "Resident Advisor",
        "Search Tracklists",
        "Share",
        "Short link",
        "Short Link",
        "Songstats",
        "SoundCloud",
        "Spotify",
        "Stories",
        "TL date",
        "Tracklist Actions",
        "Tracklist Genre(s)",
        "Tracklist Media Links",
        "Tracklists",
        "Traxsource",
        "Views",
        "Website",
        "X.com",
        "YouTube"
    ].map(value => value.toLowerCase())
);